version: "3.9"

services:
  django:
    image: test_pro
    container_name: django_app
    build: .
    volumes:
    - .:/Pro
    env_file:
      ./Pro/.env
    depends_on:
      - postgres
    ports:
      - "8020:8020"

  postgres:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      ./Pro/.env
    ports:
      - "4321:4321"
    command: -p 4321